# Pandas

การแก้ไขข้อมูล การเพิ่มข้อมูล ให้ระบุ column, row ที่ต้องการแก้ หรือ ที่ไม่มีอยู่เพื่อให้สร้างใหม่

## นำเข้าเครื่องมือ

In [1]:
import pandas as pd

## ข้อมูลที่ใช้

ไฟล์ object ที่เปิดด้วย pandas จะเรียกว่า DataFrame

In [3]:
east = pd.read_excel('excel/East.xlsx').set_index('Product')
new_column = east['Qtr1'] + east['Qtr2']

## เพิ่ม column ใหม่

In [7]:
east['first half'] = new_column

In [10]:
east

                        Qtr1  Qtr2  Qtr3  Qtr4  first half
Product
Basil Leaf (Whole)      9555  5975  5595  9659       15530
Celery Seed (Whole)     7543  7346  3466  7474       14889
Catnip Leaf              854   364   474   743        1218
Cardamom Seed (Ground)   844   848   457   744        1692
Anise Seeds              734   457   327   235        1191
Asafoetida Powder        688   468   874   568        1156
Caraway Seed (Whole)     676   856   855   866        1532
Bay Leaf (Whole)         667   799   750   575        1466
Chamomile Flowers        553   474   632   474        1027
East Special             400   751   985  1450        1151
Cardamom Seed (Whole)    379   375   377   745         754

In [9]:
east[['first half','Qtr1','Qtr2','Qtr3','Qtr4']]

                        first half  Qtr1  Qtr2  Qtr3  Qtr4
Product
Basil Leaf (Whole)           15530  9555  5975  5595  9659
Celery Seed (Whole)          14889  7543  7346  3466  7474
Catnip Leaf                   1218   854   364   474   743
Cardamom Seed (Ground)        1692   844   848   457   744
Anise Seeds                   1191   734   457   327   235
Asafoetida Powder             1156   688   468   874   568
Caraway Seed (Whole)          1532   676   856   855   866
Bay Leaf (Whole)              1466   667   799   750   575
Chamomile Flowers             1027   553   474   632   474
East Special                  1151   400   751   985  1450
Cardamom Seed (Whole)          754   379   375   377   745

## เพิ่ม row ใหม่

In [16]:
cardamom = east.loc['Cardamom Seed (Ground)'] + east.loc['Cardamom Seed (Whole)']

In [17]:
east.loc['cardamom'] = cardamom

In [18]:
east.loc['Basil Leaf (Whole)'] = cardamom

In [20]:
east['Qtr1']['Basil Leaf (Whole)'] = 9999

In [21]:
east

                        Qtr1  Qtr2  Qtr3  Qtr4  first half
Product
Basil Leaf (Whole)      9999  1223   834  1489        2446
Celery Seed (Whole)     7543  7346  3466  7474       14889
Catnip Leaf              854   364   474   743        1218
Cardamom Seed (Ground)   844   848   457   744        1692
Anise Seeds              734   457   327   235        1191
Asafoetida Powder        688   468   874   568        1156
Caraway Seed (Whole)     676   856   855   866        1532
Bay Leaf (Whole)         667   799   750   575        1466
Chamomile Flowers        553   474   632   474        1027
East Special             400   751   985  1450        1151
Cardamom Seed (Whole)    379   375   377   745         754
cardamom                1223  1223   834  1489        2446